%% show optimal fixation mark
function newFixationTex = do_fixation(options)

% Make initial fixation texture
newFixationArray(:,:,1) = zeros([ceil(options.fix.fixSizeOuter * options.PPD), ceil(options.fix.fixSizeOuter * options.PPD)]) + options.grayCol(1);
newFixationArray(:,:,2) = zeros([ceil(options.fix.fixSizeOuter * options.PPD), ceil(options.fix.fixSizeOuter * options.PPD)]) + options.grayCol(1);
newFixationArray(:,:,3) = zeros([ceil(options.fix.fixSizeOuter * options.PPD), ceil(options.fix.fixSizeOuter * options.PPD)]) + options.grayCol(1);

% Make mask for fixation circle
[xx,yy] = meshgrid(1:ceil(options.fix.fixSizeOuter*options.PPD),1:ceil(options.fix.fixSizeOuter*options.PPD));
newFixationArray(:,:,4) = false(ceil(options.fix.fixSizeOuter * options.PPD), ceil(options.fix.fixSizeOuter * options.PPD));
newFixationArray(:,:,4) = (squeeze(newFixationArray(:,:,4)) | hypot(xx - size(newFixationArray,1)/2,...
    yy - size(newFixationArray,2)/2) <= ceil(options.fix.fixSizeOuter/2*options.PPD)).*255;
newFixationTex = Screen('MakeTexture',options.windowNum,newFixationArray);

% Draw outer circle
Screen('FillOval', newFixationTex, options.fix.fixOuterOvalColor, ...
    [options.fix.fixRectX - options.fix.fixSizeOuter/2 * options.PPD, ...
    options.fix.fixRectY - options.fix.fixSizeOuter/2 * options.PPD, ...
    options.fix.fixRectX + options.fix.fixSizeOuter/2 * options.PPD, ...
    options.fix.fixRectY + options.fix.fixSizeOuter/2 * options.PPD]);

% Draw horizontal cross hair
Screen('FillRect', newFixationTex, options.fix.fixCrossColor,...
    [options.fix.fixRectX - (options.fix.fixSizeOuter/2) * options.PPD,...
    options.fix.fixRectY - (options.fix.fixSizeInner/2) * options.PPD,...
    options.fix.fixRectX + (options.fix.fixSizeOuter/2) * options.PPD,...
    options.fix.fixRectY + (options.fix.fixSizeInner/2) * options.PPD]);

% Draw vertical cross hair
Screen('FillRect', newFixationTex, options.fix.fixCrossColor,...
    [options.fix.fixRectX - (options.fix.fixSizeInner/2) * options.PPD,...
    options.fix.fixRectY - (options.fix.fixSizeOuter/2) * options.PPD,...
    options.fix.fixRectX + (options.fix.fixSizeInner/2) * options.PPD,...
    options.fix.fixRectY + (options.fix.fixSizeOuter/2) * options.PPD]);

% Draw inner circle
Screen('FillOval', newFixationTex, options.fix.fixInnerOvalColor, ...
    [options.fix.fixRectX - options.fix.fixSizeInner/2 * options.PPD, ...
    options.fix.fixRectY - options.fix.fixSizeInner/2 * options.PPD, ...
    options.fix.fixRectX + options.fix.fixSizeInner/2 * options.PPD, ...
    options.fix.fixRectY + options.fix.fixSizeInner/2 * options.PPD]);
end